{
//////////////////////////////////////////////////////////
//   This file has been automatically generated 
//     (Thu Jul 27 15:03:46 2017 by ROOT version6.08/06)
//   from TTree B2GTree/B2G TTree Ntuple
//   found on file: input_files/SingleMuonB_file999.root
//////////////////////////////////////////////////////////


//Reset ROOT and connect tree file
   gROOT->Reset();
   TFile *f = (TFile*)gROOT->GetListOfFiles()->FindObject("input_files/SingleMuonB_file999.root");
   if (!f) {
      f = new TFile("input_files/SingleMuonB_file999.root");
   }
    TDirectory * dir = (TDirectory*)f->Get("input_files/SingleMuonB_file999.root:/B2GTTreeMaker");
    dir->GetObject("B2GTree",tree);

//Declaration of leaves types
   UInt_t          evt_RunNumber;
   UInt_t          evt_LumiBlock;
   ULong64_t       evt_EventNumber;
   Int_t           pu_NtrueInt;
   Int_t           Flag_BadPFMuonFilter;
   Int_t           Flag_BadChargedCandidateFilter;
   UInt_t          met_MuCleanOnly_size;
   Float_t         met_MuCleanOnly_Pt[1];
   Float_t         met_MuCleanOnly_Phi[1];
   UInt_t          met_size;
   Float_t         met_Pt[1];
   Float_t         met_Phi[1];
   UInt_t          puppimet_size;
   Float_t         puppimet_Pt[1];
   Float_t         puppimet_Phi[1];
   UInt_t          el_size;
   Float_t         el_Pt[6];
   Float_t         el_Eta[6];
   Float_t         el_Phi[6];
   Float_t         el_E[6];
   Float_t         el_Charge[6];
   Float_t         el_Key[6];
   Float_t         el_Iso03[6];
   Float_t         el_Iso03db[6];
   Float_t         el_MiniIso[6];
   Float_t         el_rho[6];
   Float_t         el_EA[6];
   Float_t         el_sumChargedHadronPt[6];
   Float_t         el_sumNeutralHadronEt[6];
   Float_t         el_sumPhotonEt[6];
   Float_t         el_sumPUPt[6];
   Float_t         el_Dxy[6];
   Float_t         el_Dz[6];
   Float_t         el_DB[6];
   Float_t         el_DBerr[6];
   Float_t         el_dEtaIn[6];
   Float_t         el_dEtaInSeed[6];
   Float_t         el_dPhiIn[6];
   Float_t         el_HoE[6];
   Float_t         el_full5x5siee[6];
   Float_t         el_ooEmooP[6];
   Float_t         el_missHits[6];
   Float_t         el_hasMatchedConVeto[6];
   Float_t         el_SCEta[6];
   Float_t         el_SCPhi[6];
   Float_t         el_vidVeto[6];
   Float_t         el_vidLoose[6];
   Float_t         el_vidMedium[6];
   Float_t         el_vidTight[6];
   Float_t         el_vidHEEP[6];
   Float_t         el_vidVetonoiso[6];
   Float_t         el_vidLoosenoiso[6];
   Float_t         el_vidMediumnoiso[6];
   Float_t         el_vidTightnoiso[6];
   Float_t         el_vidHEEPnoiso[6];
   Float_t         el_vidMvaGPvalue[6];
   Float_t         el_vidMvaGPcateg[6];
   Float_t         el_vidMvaHZZvalue[6];
   Float_t         el_vidMvaHZZcateg[6];
   UInt_t          mu_size;
   Float_t         mu_Pt[16];
   Float_t         mu_Eta[16];
   Float_t         mu_Phi[16];
   Float_t         mu_E[16];
   Float_t         mu_Charge[16];
   Float_t         mu_Key[16];
   Float_t         mu_Iso04[16];
   Float_t         mu_MiniIso[16];
   Float_t         mu_Dxy[16];
   Float_t         mu_Dz[16];
   Float_t         mu_DB[16];
   Float_t         mu_DBerr[16];
   Float_t         mu_IsSoftMuon[16];
   Float_t         mu_IsLooseMuon[16];
   Float_t         mu_IsMediumMuon[16];
   Float_t         mu_IsMediumMuon2016[16];
   Float_t         mu_IsTightMuon[16];
   Float_t         mu_IsHighPtMuon[16];
   Float_t         mu_InnerTrackPt[16];
   Float_t         mu_TunePMuonBestTrackPt[16];
   Float_t         mu_IsPFMuon[16];
   Float_t         mu_IsGlobalMuon[16];
   Float_t         mu_IsTrackerMuon[16];
   Float_t         mu_CombQualChi2LocalPos[16];
   Float_t         mu_CombQualTrkKink[16];
   Float_t         mu_InTrkValidFraction[16];
   Float_t         mu_SegmentCompatibility[16];
   Float_t         mu_GlbTrkNormChi2[16];
   Float_t         mu_NumberValidMuonHits[16];
   Float_t         mu_NumberMatchedStations[16];
   Float_t         mu_NumberValidPixelHits[16];
   Float_t         mu_NumberTrackerLayers[16];
   Float_t         mu_NumberOfValidTrackerHits[16];
   Float_t         mu_NumberOfPixelLayers[16];
   Float_t         mu_InTrkNormChi2[16];
   Float_t         mu_SumChargedHadronPt[16];
   Float_t         mu_SumNeutralHadronPt[16];
   Float_t         mu_SumPhotonPt[16];
   Float_t         mu_SumPUPt[16];
   Float_t         mu_TrackerSumPt[16];
   Float_t         mu_GenMuonEta[16];
   Float_t         mu_GenMuonPhi[16];
   Float_t         mu_GenMuonPt[16];
   Float_t         mu_GenMuonE[16];
   Float_t         mu_GenMuonCharge[16];
   UInt_t          jetAK4CHS_size;
   Float_t         jetAK4CHS_Pt[30];
   Float_t         jetAK4CHS_Eta[30];
   Float_t         jetAK4CHS_Phi[30];
   Float_t         jetAK4CHS_E[30];
   Float_t         jetAK4CHS_Charge[30];
   Float_t         jetAK4CHS_CSVv2[30];
   Float_t         jetAK4CHS_CMVAv2[30];
   Float_t         jetAK4CHS_CvsL[30];
   Float_t         jetAK4CHS_CvsB[30];
   Float_t         jetAK4CHS_GenPartonEta[30];
   Float_t         jetAK4CHS_GenPartonPhi[30];
   Float_t         jetAK4CHS_GenPartonPt[30];
   Float_t         jetAK4CHS_GenPartonE[30];
   Float_t         jetAK4CHS_GenPartonCharge[30];
   Float_t         jetAK4CHS_PartonFlavour[30];
   Float_t         jetAK4CHS_HadronFlavour[30];
   Float_t         jetAK4CHS_GenJetEta[30];
   Float_t         jetAK4CHS_GenJetPhi[30];
   Float_t         jetAK4CHS_GenJetPt[30];
   Float_t         jetAK4CHS_GenJetE[30];
   Float_t         jetAK4CHS_GenJetCharge[30];
   Float_t         jetAK4CHS_jecFactor0[30];
   Float_t         jetAK4CHS_jecUncertainty[30];
   Float_t         jetAK4CHS_JERSF[30];
   Float_t         jetAK4CHS_JERSFUp[30];
   Float_t         jetAK4CHS_JERSFDown[30];
   Float_t         jetAK4CHS_SmearedPt[30];
   vector<vector<int> > jetAK4CHS_Keys;
   Int_t           Flag_HBHENoiseFilter;
   Int_t           Flag_HBHENoiseIsoFilter;
   Int_t           Flag_CSCTightHaloFilter;
   Int_t           Flag_CSCTightHaloTrkMuUnvetoFilter;
   Int_t           Flag_CSCTightHalo2015Filter;
   Int_t           Flag_globalTightHalo2016Filter;
   Int_t           Flag_globalSuperTightHalo2016Filter;
   Int_t           Flag_HcalStripHaloFilter;
   Int_t           Flag_hcalLaserEventFilter;
   Int_t           Flag_EcalDeadCellTriggerPrimitiveFilter;
   Int_t           Flag_EcalDeadCellBoundaryEnergyFilter;
   Int_t           Flag_goodVertices;
   Int_t           Flag_eeBadScFilter;
   Int_t           Flag_ecalLaserCorrFilter;
   Int_t           Flag_trkPOGFilters;
   Int_t           Flag_chargedHadronTrackResolutionFilter;
   Int_t           Flag_muonBadTrackFilter;
   Int_t           Flag_trkPOG_manystripclus53X;
   Int_t           Flag_trkPOG_toomanystripclus53X;
   Int_t           Flag_trkPOG_logErrorTooManyClusters;
   Int_t           Flag_METFilters;
   Int_t           Flag_badMuons;
   Int_t           Flag_duplicateMuons;
   Int_t           Flag_noBadMuons;
   Int_t           HLT_Mu17;
   Int_t           HLT_Mu17_prescale;
   Int_t           HLT_Mu20;
   Int_t           HLT_Mu20_prescale;
   Int_t           HLT_Mu27;
   Int_t           HLT_Mu27_prescale;
   Int_t           HLT_Mu50;
   Int_t           HLT_Mu50_prescale;
   Int_t           HLT_Mu55;
   Int_t           HLT_Mu55_prescale;
   Int_t           HLT_TkMu17;
   Int_t           HLT_TkMu17_prescale;
   Int_t           HLT_TkMu20;
   Int_t           HLT_TkMu20_prescale;
   Int_t           HLT_TkMu27;
   Int_t           HLT_TkMu27_prescale;
   Int_t           HLT_TkMu50;
   Int_t           HLT_TkMu50_prescale;
   Int_t           HLT_IsoMu18;
   Int_t           HLT_IsoMu18_prescale;
   Int_t           HLT_IsoMu20;
   Int_t           HLT_IsoMu20_prescale;
   Int_t           HLT_IsoMu22;
   Int_t           HLT_IsoMu22_prescale;
   Int_t           HLT_IsoMu24;
   Int_t           HLT_IsoMu24_prescale;
   Int_t           HLT_IsoMu27;
   Int_t           HLT_IsoMu27_prescale;
   Int_t           HLT_IsoTkMu18;
   Int_t           HLT_IsoTkMu18_prescale;
   Int_t           HLT_IsoTkMu20;
   Int_t           HLT_IsoTkMu20_prescale;
   Int_t           HLT_IsoTkMu22;
   Int_t           HLT_IsoTkMu22_prescale;
   Int_t           HLT_IsoTkMu24;
   Int_t           HLT_IsoTkMu24_prescale;
   Int_t           HLT_IsoTkMu27;
   Int_t           HLT_IsoTkMu27_prescale;
   Int_t           HLT_Ele17_CaloIdL_GsfTrkIdVL;
   Int_t           HLT_Ele17_CaloIdL_GsfTrkIdVL_prescale;
   Int_t           HLT_Ele22_eta2p1_WPLoose_Gsf;
   Int_t           HLT_Ele22_eta2p1_WPLoose_Gsf_prescale;
   Int_t           HLT_Ele23_WPLoose_Gsf;
   Int_t           HLT_Ele23_WPLoose_Gsf_prescale;
   Int_t           HLT_Ele24_eta2p1_WPLoose_Gsf;
   Int_t           HLT_Ele24_eta2p1_WPLoose_Gsf_prescale;
   Int_t           HLT_Ele25_WPTight_Gsf;
   Int_t           HLT_Ele25_WPTight_Gsf_prescale;
   Int_t           HLT_Ele25_eta2p1_WPLoose_Gsf;
   Int_t           HLT_Ele25_eta2p1_WPLoose_Gsf_prescale;
   Int_t           HLT_Ele25_eta2p1_WPTight_Gsf;
   Int_t           HLT_Ele25_eta2p1_WPTight_Gsf_prescale;
   Int_t           HLT_Ele27_WPLoose_Gsf;
   Int_t           HLT_Ele27_WPLoose_Gsf_prescale;
   Int_t           HLT_Ele27_WPTight_Gsf;
   Int_t           HLT_Ele27_WPTight_Gsf_prescale;
   Int_t           HLT_Ele27_eta2p1_WPLoose_Gsf;
   Int_t           HLT_Ele27_eta2p1_WPLoose_Gsf_prescale;
   Int_t           HLT_Ele27_eta2p1_WPTight_Gsf;
   Int_t           HLT_Ele27_eta2p1_WPTight_Gsf_prescale;
   Int_t           HLT_Ele30_WPTight_Gsf;
   Int_t           HLT_Ele30_WPTight_Gsf_prescale;
   Int_t           HLT_Ele30_eta2p1_WPLoose_Gsf;
   Int_t           HLT_Ele30_eta2p1_WPLoose_Gsf_prescale;
   Int_t           HLT_Ele30_eta2p1_WPTight_Gsf;
   Int_t           HLT_Ele30_eta2p1_WPTight_Gsf_prescale;
   Int_t           HLT_Ele32_WPTight_Gsf;
   Int_t           HLT_Ele32_WPTight_Gsf_prescale;
   Int_t           HLT_Ele32_eta2p1_WPLoose_Gsf;
   Int_t           HLT_Ele32_eta2p1_WPLoose_Gsf_prescale;
   Int_t           HLT_Ele32_eta2p1_WPTight_Gsf;
   Int_t           HLT_Ele32_eta2p1_WPTight_Gsf_prescale;
   Int_t           HLT_Ele35_WPLoose_Gsf;
   Int_t           HLT_Ele35_WPLoose_Gsf_prescale;
   Int_t           HLT_Ele45_WPLoose_Gsf;
   Int_t           HLT_Ele45_WPLoose_Gsf_prescale;
   Int_t           HLT_Ele105_CaloIdVT_GsfTrkIdT;
   Int_t           HLT_Ele105_CaloIdVT_GsfTrkIdT_prescale;
   Int_t           HLT_Ele115_CaloIdVT_GsfTrkIdT;
   Int_t           HLT_Ele115_CaloIdVT_GsfTrkIdT_prescale;
   Int_t           HLT_Ele145_CaloIdVT_GsfTrkIdT;
   Int_t           HLT_Ele145_CaloIdVT_GsfTrkIdT_prescale;
   Int_t           HLT_Ele200_CaloIdVT_GsfTrkIdT;
   Int_t           HLT_Ele200_CaloIdVT_GsfTrkIdT_prescale;
   Int_t           HLT_Ele250_CaloIdVT_GsfTrkIdT;
   Int_t           HLT_Ele250_CaloIdVT_GsfTrkIdT_prescale;
   Int_t           HLT_Ele300_CaloIdVT_GsfTrkIdT;
   Int_t           HLT_Ele300_CaloIdVT_GsfTrkIdT_prescale;
   Int_t           HLT_Mu30_eta2p1_PFJet150_PFJet50;
   Int_t           HLT_Mu30_eta2p1_PFJet150_PFJet50_prescale;
   Int_t           HLT_Mu40_eta2p1_PFJet200_PFJet50;
   Int_t           HLT_Mu40_eta2p1_PFJet200_PFJet50_prescale;
   Int_t           HLT_Ele35_CaloIdVT_GsfTrkIdT_PFJet150_PFJet50;
   Int_t           HLT_Ele35_CaloIdVT_GsfTrkIdT_PFJet150_PFJet50_prescale;
   Int_t           HLT_Ele45_CaloIdVT_GsfTrkIdT_PFJet200_PFJet50;
   Int_t           HLT_Ele45_CaloIdVT_GsfTrkIdT_PFJet200_PFJet50_prescale;
   Int_t           evt_NGoodVtx;
   Int_t           evt_LHA_PDF_ID;
   Int_t           evt_NIsoTrk;
   Float_t         evt_MR;
   Float_t         evt_MTR;
   Float_t         evt_R;
   Float_t         evt_R2;
   Float_t         evt_MR_Smear;
   Float_t         evt_MTR_Smear;
   Float_t         evt_XSec;
   Float_t         evt_Gen_Weight;
   Float_t         evt_Gen_Ht;
   Float_t         SUSY_Stop_Mass;
   Float_t         SUSY_Gluino_Mass;
   Float_t         SUSY_LSP_Mass;
   UInt_t          gen_size;
   Int_t           gen_ID[0];
   Int_t           gen_Status[0];
   Int_t           gen_Mom0ID[0];
   Int_t           gen_Mom0Status[0];
   Int_t           gen_Mom1ID[0];
   Int_t           gen_Mom1Status[0];
   Int_t           gen_Dau0ID[0];
   Int_t           gen_Dau0Status[0];
   Int_t           gen_Dau1ID[0];
   Int_t           gen_Dau1Status[0];
   UInt_t          scale_size;
   Float_t         scale_Weights[0];
   UInt_t          pdf_size;
   Float_t         pdf_Weights[0];
   UInt_t          alphas_size;
   Float_t         alphas_Weights[0];
   UInt_t          metsyst_size;
   Float_t         metsyst_MuCleanOnly_Pt[14];
   Float_t         metsyst_MuCleanOnly_Phi[14];
   Float_t         metsyst_Pt[14];
   Float_t         metsyst_Phi[14];
   UInt_t          puppimetsyst_size;
   Float_t         puppimetsyst_Pt[14];
   Float_t         puppimetsyst_Phi[14];
   Float_t         gen_Pt[0];
   Float_t         gen_Eta[0];
   Float_t         gen_Phi[0];
   Float_t         gen_E[0];
   Float_t         gen_Mass[0];
   Float_t         gen_Charge[0];

   // Set branch addresses.
   B2GTree->SetBranchAddress("evt_RunNumber",&evt_RunNumber);
   B2GTree->SetBranchAddress("evt_LumiBlock",&evt_LumiBlock);
   B2GTree->SetBranchAddress("evt_EventNumber",&evt_EventNumber);
   B2GTree->SetBranchAddress("pu_NtrueInt",&pu_NtrueInt);
   B2GTree->SetBranchAddress("Flag_BadPFMuonFilter",&Flag_BadPFMuonFilter);
   B2GTree->SetBranchAddress("Flag_BadChargedCandidateFilter",&Flag_BadChargedCandidateFilter);
   B2GTree->SetBranchAddress("met_MuCleanOnly_size",&met_MuCleanOnly_size);
   B2GTree->SetBranchAddress("met_MuCleanOnly_Pt",met_MuCleanOnly_Pt);
   B2GTree->SetBranchAddress("met_MuCleanOnly_Phi",met_MuCleanOnly_Phi);
   B2GTree->SetBranchAddress("met_size",&met_size);
   B2GTree->SetBranchAddress("met_Pt",met_Pt);
   B2GTree->SetBranchAddress("met_Phi",met_Phi);
   B2GTree->SetBranchAddress("puppimet_size",&puppimet_size);
   B2GTree->SetBranchAddress("puppimet_Pt",puppimet_Pt);
   B2GTree->SetBranchAddress("puppimet_Phi",puppimet_Phi);
   B2GTree->SetBranchAddress("el_size",&el_size);
   B2GTree->SetBranchAddress("el_Pt",el_Pt);
   B2GTree->SetBranchAddress("el_Eta",el_Eta);
   B2GTree->SetBranchAddress("el_Phi",el_Phi);
   B2GTree->SetBranchAddress("el_E",el_E);
   B2GTree->SetBranchAddress("el_Charge",el_Charge);
   B2GTree->SetBranchAddress("el_Key",el_Key);
   B2GTree->SetBranchAddress("el_Iso03",el_Iso03);
   B2GTree->SetBranchAddress("el_Iso03db",el_Iso03db);
   B2GTree->SetBranchAddress("el_MiniIso",el_MiniIso);
   B2GTree->SetBranchAddress("el_rho",el_rho);
   B2GTree->SetBranchAddress("el_EA",el_EA);
   B2GTree->SetBranchAddress("el_sumChargedHadronPt",el_sumChargedHadronPt);
   B2GTree->SetBranchAddress("el_sumNeutralHadronEt",el_sumNeutralHadronEt);
   B2GTree->SetBranchAddress("el_sumPhotonEt",el_sumPhotonEt);
   B2GTree->SetBranchAddress("el_sumPUPt",el_sumPUPt);
   B2GTree->SetBranchAddress("el_Dxy",el_Dxy);
   B2GTree->SetBranchAddress("el_Dz",el_Dz);
   B2GTree->SetBranchAddress("el_DB",el_DB);
   B2GTree->SetBranchAddress("el_DBerr",el_DBerr);
   B2GTree->SetBranchAddress("el_dEtaIn",el_dEtaIn);
   B2GTree->SetBranchAddress("el_dEtaInSeed",el_dEtaInSeed);
   B2GTree->SetBranchAddress("el_dPhiIn",el_dPhiIn);
   B2GTree->SetBranchAddress("el_HoE",el_HoE);
   B2GTree->SetBranchAddress("el_full5x5siee",el_full5x5siee);
   B2GTree->SetBranchAddress("el_ooEmooP",el_ooEmooP);
   B2GTree->SetBranchAddress("el_missHits",el_missHits);
   B2GTree->SetBranchAddress("el_hasMatchedConVeto",el_hasMatchedConVeto);
   B2GTree->SetBranchAddress("el_SCEta",el_SCEta);
   B2GTree->SetBranchAddress("el_SCPhi",el_SCPhi);
   B2GTree->SetBranchAddress("el_vidVeto",el_vidVeto);
   B2GTree->SetBranchAddress("el_vidLoose",el_vidLoose);
   B2GTree->SetBranchAddress("el_vidMedium",el_vidMedium);
   B2GTree->SetBranchAddress("el_vidTight",el_vidTight);
   B2GTree->SetBranchAddress("el_vidHEEP",el_vidHEEP);
   B2GTree->SetBranchAddress("el_vidVetonoiso",el_vidVetonoiso);
   B2GTree->SetBranchAddress("el_vidLoosenoiso",el_vidLoosenoiso);
   B2GTree->SetBranchAddress("el_vidMediumnoiso",el_vidMediumnoiso);
   B2GTree->SetBranchAddress("el_vidTightnoiso",el_vidTightnoiso);
   B2GTree->SetBranchAddress("el_vidHEEPnoiso",el_vidHEEPnoiso);
   B2GTree->SetBranchAddress("el_vidMvaGPvalue",el_vidMvaGPvalue);
   B2GTree->SetBranchAddress("el_vidMvaGPcateg",el_vidMvaGPcateg);
   B2GTree->SetBranchAddress("el_vidMvaHZZvalue",el_vidMvaHZZvalue);
   B2GTree->SetBranchAddress("el_vidMvaHZZcateg",el_vidMvaHZZcateg);
   B2GTree->SetBranchAddress("mu_size",&mu_size);
   B2GTree->SetBranchAddress("mu_Pt",mu_Pt);
   B2GTree->SetBranchAddress("mu_Eta",mu_Eta);
   B2GTree->SetBranchAddress("mu_Phi",mu_Phi);
   B2GTree->SetBranchAddress("mu_E",mu_E);
   B2GTree->SetBranchAddress("mu_Charge",mu_Charge);
   B2GTree->SetBranchAddress("mu_Key",mu_Key);
   B2GTree->SetBranchAddress("mu_Iso04",mu_Iso04);
   B2GTree->SetBranchAddress("mu_MiniIso",mu_MiniIso);
   B2GTree->SetBranchAddress("mu_Dxy",mu_Dxy);
   B2GTree->SetBranchAddress("mu_Dz",mu_Dz);
   B2GTree->SetBranchAddress("mu_DB",mu_DB);
   B2GTree->SetBranchAddress("mu_DBerr",mu_DBerr);
   B2GTree->SetBranchAddress("mu_IsSoftMuon",mu_IsSoftMuon);
   B2GTree->SetBranchAddress("mu_IsLooseMuon",mu_IsLooseMuon);
   B2GTree->SetBranchAddress("mu_IsMediumMuon",mu_IsMediumMuon);
   B2GTree->SetBranchAddress("mu_IsMediumMuon2016",mu_IsMediumMuon2016);
   B2GTree->SetBranchAddress("mu_IsTightMuon",mu_IsTightMuon);
   B2GTree->SetBranchAddress("mu_IsHighPtMuon",mu_IsHighPtMuon);
   B2GTree->SetBranchAddress("mu_InnerTrackPt",mu_InnerTrackPt);
   B2GTree->SetBranchAddress("mu_TunePMuonBestTrackPt",mu_TunePMuonBestTrackPt);
   B2GTree->SetBranchAddress("mu_IsPFMuon",mu_IsPFMuon);
   B2GTree->SetBranchAddress("mu_IsGlobalMuon",mu_IsGlobalMuon);
   B2GTree->SetBranchAddress("mu_IsTrackerMuon",mu_IsTrackerMuon);
   B2GTree->SetBranchAddress("mu_CombQualChi2LocalPos",mu_CombQualChi2LocalPos);
   B2GTree->SetBranchAddress("mu_CombQualTrkKink",mu_CombQualTrkKink);
   B2GTree->SetBranchAddress("mu_InTrkValidFraction",mu_InTrkValidFraction);
   B2GTree->SetBranchAddress("mu_SegmentCompatibility",mu_SegmentCompatibility);
   B2GTree->SetBranchAddress("mu_GlbTrkNormChi2",mu_GlbTrkNormChi2);
   B2GTree->SetBranchAddress("mu_NumberValidMuonHits",mu_NumberValidMuonHits);
   B2GTree->SetBranchAddress("mu_NumberMatchedStations",mu_NumberMatchedStations);
   B2GTree->SetBranchAddress("mu_NumberValidPixelHits",mu_NumberValidPixelHits);
   B2GTree->SetBranchAddress("mu_NumberTrackerLayers",mu_NumberTrackerLayers);
   B2GTree->SetBranchAddress("mu_NumberOfValidTrackerHits",mu_NumberOfValidTrackerHits);
   B2GTree->SetBranchAddress("mu_NumberOfPixelLayers",mu_NumberOfPixelLayers);
   B2GTree->SetBranchAddress("mu_InTrkNormChi2",mu_InTrkNormChi2);
   B2GTree->SetBranchAddress("mu_SumChargedHadronPt",mu_SumChargedHadronPt);
   B2GTree->SetBranchAddress("mu_SumNeutralHadronPt",mu_SumNeutralHadronPt);
   B2GTree->SetBranchAddress("mu_SumPhotonPt",mu_SumPhotonPt);
   B2GTree->SetBranchAddress("mu_SumPUPt",mu_SumPUPt);
   B2GTree->SetBranchAddress("mu_TrackerSumPt",mu_TrackerSumPt);
   B2GTree->SetBranchAddress("mu_GenMuonEta",mu_GenMuonEta);
   B2GTree->SetBranchAddress("mu_GenMuonPhi",mu_GenMuonPhi);
   B2GTree->SetBranchAddress("mu_GenMuonPt",mu_GenMuonPt);
   B2GTree->SetBranchAddress("mu_GenMuonE",mu_GenMuonE);
   B2GTree->SetBranchAddress("mu_GenMuonCharge",mu_GenMuonCharge);
   B2GTree->SetBranchAddress("jetAK4CHS_size",&jetAK4CHS_size);
   B2GTree->SetBranchAddress("jetAK4CHS_Pt",jetAK4CHS_Pt);
   B2GTree->SetBranchAddress("jetAK4CHS_Eta",jetAK4CHS_Eta);
   B2GTree->SetBranchAddress("jetAK4CHS_Phi",jetAK4CHS_Phi);
   B2GTree->SetBranchAddress("jetAK4CHS_E",jetAK4CHS_E);
   B2GTree->SetBranchAddress("jetAK4CHS_Charge",jetAK4CHS_Charge);
   B2GTree->SetBranchAddress("jetAK4CHS_CSVv2",jetAK4CHS_CSVv2);
   B2GTree->SetBranchAddress("jetAK4CHS_CMVAv2",jetAK4CHS_CMVAv2);
   B2GTree->SetBranchAddress("jetAK4CHS_CvsL",jetAK4CHS_CvsL);
   B2GTree->SetBranchAddress("jetAK4CHS_CvsB",jetAK4CHS_CvsB);
   B2GTree->SetBranchAddress("jetAK4CHS_GenPartonEta",jetAK4CHS_GenPartonEta);
   B2GTree->SetBranchAddress("jetAK4CHS_GenPartonPhi",jetAK4CHS_GenPartonPhi);
   B2GTree->SetBranchAddress("jetAK4CHS_GenPartonPt",jetAK4CHS_GenPartonPt);
   B2GTree->SetBranchAddress("jetAK4CHS_GenPartonE",jetAK4CHS_GenPartonE);
   B2GTree->SetBranchAddress("jetAK4CHS_GenPartonCharge",jetAK4CHS_GenPartonCharge);
   B2GTree->SetBranchAddress("jetAK4CHS_PartonFlavour",jetAK4CHS_PartonFlavour);
   B2GTree->SetBranchAddress("jetAK4CHS_HadronFlavour",jetAK4CHS_HadronFlavour);
   B2GTree->SetBranchAddress("jetAK4CHS_GenJetEta",jetAK4CHS_GenJetEta);
   B2GTree->SetBranchAddress("jetAK4CHS_GenJetPhi",jetAK4CHS_GenJetPhi);
   B2GTree->SetBranchAddress("jetAK4CHS_GenJetPt",jetAK4CHS_GenJetPt);
   B2GTree->SetBranchAddress("jetAK4CHS_GenJetE",jetAK4CHS_GenJetE);
   B2GTree->SetBranchAddress("jetAK4CHS_GenJetCharge",jetAK4CHS_GenJetCharge);
   B2GTree->SetBranchAddress("jetAK4CHS_jecFactor0",jetAK4CHS_jecFactor0);
   B2GTree->SetBranchAddress("jetAK4CHS_jecUncertainty",jetAK4CHS_jecUncertainty);
   B2GTree->SetBranchAddress("jetAK4CHS_JERSF",jetAK4CHS_JERSF);
   B2GTree->SetBranchAddress("jetAK4CHS_JERSFUp",jetAK4CHS_JERSFUp);
   B2GTree->SetBranchAddress("jetAK4CHS_JERSFDown",jetAK4CHS_JERSFDown);
   B2GTree->SetBranchAddress("jetAK4CHS_SmearedPt",jetAK4CHS_SmearedPt);
   B2GTree->SetBranchAddress("jetAK4CHS_Keys",&jetAK4CHS_Keys);
   B2GTree->SetBranchAddress("Flag_HBHENoiseFilter",&Flag_HBHENoiseFilter);
   B2GTree->SetBranchAddress("Flag_HBHENoiseIsoFilter",&Flag_HBHENoiseIsoFilter);
   B2GTree->SetBranchAddress("Flag_CSCTightHaloFilter",&Flag_CSCTightHaloFilter);
   B2GTree->SetBranchAddress("Flag_CSCTightHaloTrkMuUnvetoFilter",&Flag_CSCTightHaloTrkMuUnvetoFilter);
   B2GTree->SetBranchAddress("Flag_CSCTightHalo2015Filter",&Flag_CSCTightHalo2015Filter);
   B2GTree->SetBranchAddress("Flag_globalTightHalo2016Filter",&Flag_globalTightHalo2016Filter);
   B2GTree->SetBranchAddress("Flag_globalSuperTightHalo2016Filter",&Flag_globalSuperTightHalo2016Filter);
   B2GTree->SetBranchAddress("Flag_HcalStripHaloFilter",&Flag_HcalStripHaloFilter);
   B2GTree->SetBranchAddress("Flag_hcalLaserEventFilter",&Flag_hcalLaserEventFilter);
   B2GTree->SetBranchAddress("Flag_EcalDeadCellTriggerPrimitiveFilter",&Flag_EcalDeadCellTriggerPrimitiveFilter);
   B2GTree->SetBranchAddress("Flag_EcalDeadCellBoundaryEnergyFilter",&Flag_EcalDeadCellBoundaryEnergyFilter);
   B2GTree->SetBranchAddress("Flag_goodVertices",&Flag_goodVertices);
   B2GTree->SetBranchAddress("Flag_eeBadScFilter",&Flag_eeBadScFilter);
   B2GTree->SetBranchAddress("Flag_ecalLaserCorrFilter",&Flag_ecalLaserCorrFilter);
   B2GTree->SetBranchAddress("Flag_trkPOGFilters",&Flag_trkPOGFilters);
   B2GTree->SetBranchAddress("Flag_chargedHadronTrackResolutionFilter",&Flag_chargedHadronTrackResolutionFilter);
   B2GTree->SetBranchAddress("Flag_muonBadTrackFilter",&Flag_muonBadTrackFilter);
   B2GTree->SetBranchAddress("Flag_trkPOG_manystripclus53X",&Flag_trkPOG_manystripclus53X);
   B2GTree->SetBranchAddress("Flag_trkPOG_toomanystripclus53X",&Flag_trkPOG_toomanystripclus53X);
   B2GTree->SetBranchAddress("Flag_trkPOG_logErrorTooManyClusters",&Flag_trkPOG_logErrorTooManyClusters);
   B2GTree->SetBranchAddress("Flag_METFilters",&Flag_METFilters);
   B2GTree->SetBranchAddress("Flag_badMuons",&Flag_badMuons);
   B2GTree->SetBranchAddress("Flag_duplicateMuons",&Flag_duplicateMuons);
   B2GTree->SetBranchAddress("Flag_noBadMuons",&Flag_noBadMuons);
   B2GTree->SetBranchAddress("HLT_Mu17",&HLT_Mu17);
   B2GTree->SetBranchAddress("HLT_Mu17_prescale",&HLT_Mu17_prescale);
   B2GTree->SetBranchAddress("HLT_Mu20",&HLT_Mu20);
   B2GTree->SetBranchAddress("HLT_Mu20_prescale",&HLT_Mu20_prescale);
   B2GTree->SetBranchAddress("HLT_Mu27",&HLT_Mu27);
   B2GTree->SetBranchAddress("HLT_Mu27_prescale",&HLT_Mu27_prescale);
   B2GTree->SetBranchAddress("HLT_Mu50",&HLT_Mu50);
   B2GTree->SetBranchAddress("HLT_Mu50_prescale",&HLT_Mu50_prescale);
   B2GTree->SetBranchAddress("HLT_Mu55",&HLT_Mu55);
   B2GTree->SetBranchAddress("HLT_Mu55_prescale",&HLT_Mu55_prescale);
   B2GTree->SetBranchAddress("HLT_TkMu17",&HLT_TkMu17);
   B2GTree->SetBranchAddress("HLT_TkMu17_prescale",&HLT_TkMu17_prescale);
   B2GTree->SetBranchAddress("HLT_TkMu20",&HLT_TkMu20);
   B2GTree->SetBranchAddress("HLT_TkMu20_prescale",&HLT_TkMu20_prescale);
   B2GTree->SetBranchAddress("HLT_TkMu27",&HLT_TkMu27);
   B2GTree->SetBranchAddress("HLT_TkMu27_prescale",&HLT_TkMu27_prescale);
   B2GTree->SetBranchAddress("HLT_TkMu50",&HLT_TkMu50);
   B2GTree->SetBranchAddress("HLT_TkMu50_prescale",&HLT_TkMu50_prescale);
   B2GTree->SetBranchAddress("HLT_IsoMu18",&HLT_IsoMu18);
   B2GTree->SetBranchAddress("HLT_IsoMu18_prescale",&HLT_IsoMu18_prescale);
   B2GTree->SetBranchAddress("HLT_IsoMu20",&HLT_IsoMu20);
   B2GTree->SetBranchAddress("HLT_IsoMu20_prescale",&HLT_IsoMu20_prescale);
   B2GTree->SetBranchAddress("HLT_IsoMu22",&HLT_IsoMu22);
   B2GTree->SetBranchAddress("HLT_IsoMu22_prescale",&HLT_IsoMu22_prescale);
   B2GTree->SetBranchAddress("HLT_IsoMu24",&HLT_IsoMu24);
   B2GTree->SetBranchAddress("HLT_IsoMu24_prescale",&HLT_IsoMu24_prescale);
   B2GTree->SetBranchAddress("HLT_IsoMu27",&HLT_IsoMu27);
   B2GTree->SetBranchAddress("HLT_IsoMu27_prescale",&HLT_IsoMu27_prescale);
   B2GTree->SetBranchAddress("HLT_IsoTkMu18",&HLT_IsoTkMu18);
   B2GTree->SetBranchAddress("HLT_IsoTkMu18_prescale",&HLT_IsoTkMu18_prescale);
   B2GTree->SetBranchAddress("HLT_IsoTkMu20",&HLT_IsoTkMu20);
   B2GTree->SetBranchAddress("HLT_IsoTkMu20_prescale",&HLT_IsoTkMu20_prescale);
   B2GTree->SetBranchAddress("HLT_IsoTkMu22",&HLT_IsoTkMu22);
   B2GTree->SetBranchAddress("HLT_IsoTkMu22_prescale",&HLT_IsoTkMu22_prescale);
   B2GTree->SetBranchAddress("HLT_IsoTkMu24",&HLT_IsoTkMu24);
   B2GTree->SetBranchAddress("HLT_IsoTkMu24_prescale",&HLT_IsoTkMu24_prescale);
   B2GTree->SetBranchAddress("HLT_IsoTkMu27",&HLT_IsoTkMu27);
   B2GTree->SetBranchAddress("HLT_IsoTkMu27_prescale",&HLT_IsoTkMu27_prescale);
   B2GTree->SetBranchAddress("HLT_Ele17_CaloIdL_GsfTrkIdVL",&HLT_Ele17_CaloIdL_GsfTrkIdVL);
   B2GTree->SetBranchAddress("HLT_Ele17_CaloIdL_GsfTrkIdVL_prescale",&HLT_Ele17_CaloIdL_GsfTrkIdVL_prescale);
   B2GTree->SetBranchAddress("HLT_Ele22_eta2p1_WPLoose_Gsf",&HLT_Ele22_eta2p1_WPLoose_Gsf);
   B2GTree->SetBranchAddress("HLT_Ele22_eta2p1_WPLoose_Gsf_prescale",&HLT_Ele22_eta2p1_WPLoose_Gsf_prescale);
   B2GTree->SetBranchAddress("HLT_Ele23_WPLoose_Gsf",&HLT_Ele23_WPLoose_Gsf);
   B2GTree->SetBranchAddress("HLT_Ele23_WPLoose_Gsf_prescale",&HLT_Ele23_WPLoose_Gsf_prescale);
   B2GTree->SetBranchAddress("HLT_Ele24_eta2p1_WPLoose_Gsf",&HLT_Ele24_eta2p1_WPLoose_Gsf);
   B2GTree->SetBranchAddress("HLT_Ele24_eta2p1_WPLoose_Gsf_prescale",&HLT_Ele24_eta2p1_WPLoose_Gsf_prescale);
   B2GTree->SetBranchAddress("HLT_Ele25_WPTight_Gsf",&HLT_Ele25_WPTight_Gsf);
   B2GTree->SetBranchAddress("HLT_Ele25_WPTight_Gsf_prescale",&HLT_Ele25_WPTight_Gsf_prescale);
   B2GTree->SetBranchAddress("HLT_Ele25_eta2p1_WPLoose_Gsf",&HLT_Ele25_eta2p1_WPLoose_Gsf);
   B2GTree->SetBranchAddress("HLT_Ele25_eta2p1_WPLoose_Gsf_prescale",&HLT_Ele25_eta2p1_WPLoose_Gsf_prescale);
   B2GTree->SetBranchAddress("HLT_Ele25_eta2p1_WPTight_Gsf",&HLT_Ele25_eta2p1_WPTight_Gsf);
   B2GTree->SetBranchAddress("HLT_Ele25_eta2p1_WPTight_Gsf_prescale",&HLT_Ele25_eta2p1_WPTight_Gsf_prescale);
   B2GTree->SetBranchAddress("HLT_Ele27_WPLoose_Gsf",&HLT_Ele27_WPLoose_Gsf);
   B2GTree->SetBranchAddress("HLT_Ele27_WPLoose_Gsf_prescale",&HLT_Ele27_WPLoose_Gsf_prescale);
   B2GTree->SetBranchAddress("HLT_Ele27_WPTight_Gsf",&HLT_Ele27_WPTight_Gsf);
   B2GTree->SetBranchAddress("HLT_Ele27_WPTight_Gsf_prescale",&HLT_Ele27_WPTight_Gsf_prescale);
   B2GTree->SetBranchAddress("HLT_Ele27_eta2p1_WPLoose_Gsf",&HLT_Ele27_eta2p1_WPLoose_Gsf);
   B2GTree->SetBranchAddress("HLT_Ele27_eta2p1_WPLoose_Gsf_prescale",&HLT_Ele27_eta2p1_WPLoose_Gsf_prescale);
   B2GTree->SetBranchAddress("HLT_Ele27_eta2p1_WPTight_Gsf",&HLT_Ele27_eta2p1_WPTight_Gsf);
   B2GTree->SetBranchAddress("HLT_Ele27_eta2p1_WPTight_Gsf_prescale",&HLT_Ele27_eta2p1_WPTight_Gsf_prescale);
   B2GTree->SetBranchAddress("HLT_Ele30_WPTight_Gsf",&HLT_Ele30_WPTight_Gsf);
   B2GTree->SetBranchAddress("HLT_Ele30_WPTight_Gsf_prescale",&HLT_Ele30_WPTight_Gsf_prescale);
   B2GTree->SetBranchAddress("HLT_Ele30_eta2p1_WPLoose_Gsf",&HLT_Ele30_eta2p1_WPLoose_Gsf);
   B2GTree->SetBranchAddress("HLT_Ele30_eta2p1_WPLoose_Gsf_prescale",&HLT_Ele30_eta2p1_WPLoose_Gsf_prescale);
   B2GTree->SetBranchAddress("HLT_Ele30_eta2p1_WPTight_Gsf",&HLT_Ele30_eta2p1_WPTight_Gsf);
   B2GTree->SetBranchAddress("HLT_Ele30_eta2p1_WPTight_Gsf_prescale",&HLT_Ele30_eta2p1_WPTight_Gsf_prescale);
   B2GTree->SetBranchAddress("HLT_Ele32_WPTight_Gsf",&HLT_Ele32_WPTight_Gsf);
   B2GTree->SetBranchAddress("HLT_Ele32_WPTight_Gsf_prescale",&HLT_Ele32_WPTight_Gsf_prescale);
   B2GTree->SetBranchAddress("HLT_Ele32_eta2p1_WPLoose_Gsf",&HLT_Ele32_eta2p1_WPLoose_Gsf);
   B2GTree->SetBranchAddress("HLT_Ele32_eta2p1_WPLoose_Gsf_prescale",&HLT_Ele32_eta2p1_WPLoose_Gsf_prescale);
   B2GTree->SetBranchAddress("HLT_Ele32_eta2p1_WPTight_Gsf",&HLT_Ele32_eta2p1_WPTight_Gsf);
   B2GTree->SetBranchAddress("HLT_Ele32_eta2p1_WPTight_Gsf_prescale",&HLT_Ele32_eta2p1_WPTight_Gsf_prescale);
   B2GTree->SetBranchAddress("HLT_Ele35_WPLoose_Gsf",&HLT_Ele35_WPLoose_Gsf);
   B2GTree->SetBranchAddress("HLT_Ele35_WPLoose_Gsf_prescale",&HLT_Ele35_WPLoose_Gsf_prescale);
   B2GTree->SetBranchAddress("HLT_Ele45_WPLoose_Gsf",&HLT_Ele45_WPLoose_Gsf);
   B2GTree->SetBranchAddress("HLT_Ele45_WPLoose_Gsf_prescale",&HLT_Ele45_WPLoose_Gsf_prescale);
   B2GTree->SetBranchAddress("HLT_Ele105_CaloIdVT_GsfTrkIdT",&HLT_Ele105_CaloIdVT_GsfTrkIdT);
   B2GTree->SetBranchAddress("HLT_Ele105_CaloIdVT_GsfTrkIdT_prescale",&HLT_Ele105_CaloIdVT_GsfTrkIdT_prescale);
   B2GTree->SetBranchAddress("HLT_Ele115_CaloIdVT_GsfTrkIdT",&HLT_Ele115_CaloIdVT_GsfTrkIdT);
   B2GTree->SetBranchAddress("HLT_Ele115_CaloIdVT_GsfTrkIdT_prescale",&HLT_Ele115_CaloIdVT_GsfTrkIdT_prescale);
   B2GTree->SetBranchAddress("HLT_Ele145_CaloIdVT_GsfTrkIdT",&HLT_Ele145_CaloIdVT_GsfTrkIdT);
   B2GTree->SetBranchAddress("HLT_Ele145_CaloIdVT_GsfTrkIdT_prescale",&HLT_Ele145_CaloIdVT_GsfTrkIdT_prescale);
   B2GTree->SetBranchAddress("HLT_Ele200_CaloIdVT_GsfTrkIdT",&HLT_Ele200_CaloIdVT_GsfTrkIdT);
   B2GTree->SetBranchAddress("HLT_Ele200_CaloIdVT_GsfTrkIdT_prescale",&HLT_Ele200_CaloIdVT_GsfTrkIdT_prescale);
   B2GTree->SetBranchAddress("HLT_Ele250_CaloIdVT_GsfTrkIdT",&HLT_Ele250_CaloIdVT_GsfTrkIdT);
   B2GTree->SetBranchAddress("HLT_Ele250_CaloIdVT_GsfTrkIdT_prescale",&HLT_Ele250_CaloIdVT_GsfTrkIdT_prescale);
   B2GTree->SetBranchAddress("HLT_Ele300_CaloIdVT_GsfTrkIdT",&HLT_Ele300_CaloIdVT_GsfTrkIdT);
   B2GTree->SetBranchAddress("HLT_Ele300_CaloIdVT_GsfTrkIdT_prescale",&HLT_Ele300_CaloIdVT_GsfTrkIdT_prescale);
   B2GTree->SetBranchAddress("HLT_Mu30_eta2p1_PFJet150_PFJet50",&HLT_Mu30_eta2p1_PFJet150_PFJet50);
   B2GTree->SetBranchAddress("HLT_Mu30_eta2p1_PFJet150_PFJet50_prescale",&HLT_Mu30_eta2p1_PFJet150_PFJet50_prescale);
   B2GTree->SetBranchAddress("HLT_Mu40_eta2p1_PFJet200_PFJet50",&HLT_Mu40_eta2p1_PFJet200_PFJet50);
   B2GTree->SetBranchAddress("HLT_Mu40_eta2p1_PFJet200_PFJet50_prescale",&HLT_Mu40_eta2p1_PFJet200_PFJet50_prescale);
   B2GTree->SetBranchAddress("HLT_Ele35_CaloIdVT_GsfTrkIdT_PFJet150_PFJet50",&HLT_Ele35_CaloIdVT_GsfTrkIdT_PFJet150_PFJet50);
   B2GTree->SetBranchAddress("HLT_Ele35_CaloIdVT_GsfTrkIdT_PFJet150_PFJet50_prescale",&HLT_Ele35_CaloIdVT_GsfTrkIdT_PFJet150_PFJet50_prescale);
   B2GTree->SetBranchAddress("HLT_Ele45_CaloIdVT_GsfTrkIdT_PFJet200_PFJet50",&HLT_Ele45_CaloIdVT_GsfTrkIdT_PFJet200_PFJet50);
   B2GTree->SetBranchAddress("HLT_Ele45_CaloIdVT_GsfTrkIdT_PFJet200_PFJet50_prescale",&HLT_Ele45_CaloIdVT_GsfTrkIdT_PFJet200_PFJet50_prescale);
   B2GTree->SetBranchAddress("evt_NGoodVtx",&evt_NGoodVtx);
   B2GTree->SetBranchAddress("evt_LHA_PDF_ID",&evt_LHA_PDF_ID);
   B2GTree->SetBranchAddress("evt_NIsoTrk",&evt_NIsoTrk);
   B2GTree->SetBranchAddress("evt_MR",&evt_MR);
   B2GTree->SetBranchAddress("evt_MTR",&evt_MTR);
   B2GTree->SetBranchAddress("evt_R",&evt_R);
   B2GTree->SetBranchAddress("evt_R2",&evt_R2);
   B2GTree->SetBranchAddress("evt_MR_Smear",&evt_MR_Smear);
   B2GTree->SetBranchAddress("evt_MTR_Smear",&evt_MTR_Smear);
   B2GTree->SetBranchAddress("evt_XSec",&evt_XSec);
   B2GTree->SetBranchAddress("evt_Gen_Weight",&evt_Gen_Weight);
   B2GTree->SetBranchAddress("evt_Gen_Ht",&evt_Gen_Ht);
   B2GTree->SetBranchAddress("SUSY_Stop_Mass",&SUSY_Stop_Mass);
   B2GTree->SetBranchAddress("SUSY_Gluino_Mass",&SUSY_Gluino_Mass);
   B2GTree->SetBranchAddress("SUSY_LSP_Mass",&SUSY_LSP_Mass);
   B2GTree->SetBranchAddress("gen_size",&gen_size);
   B2GTree->SetBranchAddress("gen_ID",&gen_ID);
   B2GTree->SetBranchAddress("gen_Status",&gen_Status);
   B2GTree->SetBranchAddress("gen_Mom0ID",&gen_Mom0ID);
   B2GTree->SetBranchAddress("gen_Mom0Status",&gen_Mom0Status);
   B2GTree->SetBranchAddress("gen_Mom1ID",&gen_Mom1ID);
   B2GTree->SetBranchAddress("gen_Mom1Status",&gen_Mom1Status);
   B2GTree->SetBranchAddress("gen_Dau0ID",&gen_Dau0ID);
   B2GTree->SetBranchAddress("gen_Dau0Status",&gen_Dau0Status);
   B2GTree->SetBranchAddress("gen_Dau1ID",&gen_Dau1ID);
   B2GTree->SetBranchAddress("gen_Dau1Status",&gen_Dau1Status);
   B2GTree->SetBranchAddress("scale_size",&scale_size);
   B2GTree->SetBranchAddress("scale_Weights",&scale_Weights);
   B2GTree->SetBranchAddress("pdf_size",&pdf_size);
   B2GTree->SetBranchAddress("pdf_Weights",&pdf_Weights);
   B2GTree->SetBranchAddress("alphas_size",&alphas_size);
   B2GTree->SetBranchAddress("alphas_Weights",&alphas_Weights);
   B2GTree->SetBranchAddress("metsyst_size",&metsyst_size);
   B2GTree->SetBranchAddress("metsyst_MuCleanOnly_Pt",metsyst_MuCleanOnly_Pt);
   B2GTree->SetBranchAddress("metsyst_MuCleanOnly_Phi",metsyst_MuCleanOnly_Phi);
   B2GTree->SetBranchAddress("metsyst_Pt",metsyst_Pt);
   B2GTree->SetBranchAddress("metsyst_Phi",metsyst_Phi);
   B2GTree->SetBranchAddress("puppimetsyst_size",&puppimetsyst_size);
   B2GTree->SetBranchAddress("puppimetsyst_Pt",puppimetsyst_Pt);
   B2GTree->SetBranchAddress("puppimetsyst_Phi",puppimetsyst_Phi);
   B2GTree->SetBranchAddress("gen_Pt",&gen_Pt);
   B2GTree->SetBranchAddress("gen_Eta",&gen_Eta);
   B2GTree->SetBranchAddress("gen_Phi",&gen_Phi);
   B2GTree->SetBranchAddress("gen_E",&gen_E);
   B2GTree->SetBranchAddress("gen_Mass",&gen_Mass);
   B2GTree->SetBranchAddress("gen_Charge",&gen_Charge);

//     This is the loop skeleton
//       To read only selected branches, Insert statements like:
// B2GTree->SetBranchStatus("*",0);  // disable all branches
// TTreePlayer->SetBranchStatus("branchname",1);  // activate branchname

   Long64_t nentries = B2GTree->GetEntries();

   Long64_t nbytes = 0;
//   for (Long64_t i=0; i<nentries;i++) {
//      nbytes += B2GTree->GetEntry(i);
//   }
}
